config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'
  get '/reservations' => 'reservations#index', as: :reservations
  resources :restaurants do 
    resources :reservations, only: [:edit, :create, :update, :destroy]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :cuisines, only: [:index, :show], param: :name

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  #Associations
  has_many :reservations
  has_many :users, through: :reservations
  has_and_belongs_to_many :cuisines
  
  #Validation
  validates :name, :address, :capacity, presence: true
  validates :name,              #assumed English alphabet
    length: { maximum: 100 },
    format: { with: /\A[a-zA-Z\s\-]*\Z/, message: 'must be alphabetical' }    
  validates :address,           #assumed English alphabet, catch-all field for all info (incl. postcode)
    length: { maximum: 300 },
    format: { with: /\A[A-Za-z\d\s\-,#.\/]*\Z/, message: 'must be alphanumeric' }    
  validates :capacity, numericality: { :greater_than => 0, :only_integer => true }
  validates :business_number,   #TODO: this together with a has_and_belongs_to_many association with an Owner 
    length: { is: 9 },          #model would allow basic discrimination between owners and plain users 
    :allow_blank => true,       #and, by extension, better authorization 
    numericality: { :greater_than_or_equal_to => 0, :only_integer => true }
  validate :at_least_one_cuisine

  #Capacity is assumed to refer to that during a certain time slot. The latter is defined by a starting
  #date_and_time plus a certain time length, presumed to be equal across all reservations. That time length
  #is 1 hour. All this translates into simpler criteria when calculating current remaining capacity: consider 
  #only reservations with same date and time.
  def available?(size, date_and_time)
    reserved = reservations.where(date_and_time: date_and_time).sum(:size)
    reserved + size <= capacity
  end

  #All restaurants are expected to specialize in one or more cuisines.
  private
  def at_least_one_cuisine
    errors.add(:base, 'You must select at least one type of cuisine') if cuisines.blank?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  RESTAURANT_ATTR = [:name, :address, :business_number, :capacity, {:cuisine_ids => []}]
  before_filter -> { load_restaurant(:id) }, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(secure_params(:restaurant, RESTAURANT_ATTR))
    if @restaurant.save
      redirect_to restaurants_path, notice: "Restaurant created successfully"
    else
      flash.now['alert'] = 'Failure when creating restaurant'
      render :new
    end
  end

  def update
    if @restaurant.update_attributes(secure_params(:restaurant, RESTAURANT_ATTR))
      redirect_to restaurant_path, notice: "Restaurant updated successfully"
    else
      flash.now['alert'] = 'Failure when updating restaurant'
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, notice: "Restaurant deleted"
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= render 'shared/form_header', :errors => @restaurant.errors %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :business_number %><br />
    <%= f.number_field :business_number %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </div>
  <fieldset>
    <legend>Cuisine(s)</legend>
    <%= hidden_field_tag "restaurant[cuisine_ids][]", nil %>     <!-- fallback for no checked boxes -->
    <% Cuisine.order(:name).each do |cuisine| %>
      <%= label_tag dom_id(cuisine) do %>
        <%= check_box_tag dom_id(cuisine), cuisine.id, @restaurant.cuisines.include?(cuisine), :name => 'restaurant[cuisine_ids][]' %>
        <%= cuisine.name %>
      <% end %>
    <% end %>
  </fieldset>
  <div class="actions">
    <% if @restaurant.errors.any? %>
      <p class="error">Please, make sure all fields are correct before submitting</p> 
    <% end %>
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<%= link_to restaurant_path(restaurant) do %>
  <dl>
    <dt><%= restaurant.name %></dt>
    <dd>Address: <%= restaurant.address %></dd>
    <% unless restaurant.business_number.blank? %>
      <dd>Business number: <%= restaurant.business_number %></dd>
    <% end %>
    <dd>Capacity: <%= restaurant.capacity %></dd>
    <dd>Cuisine(s):
      <ul>
        <% restaurant.cuisines.pluck(:name).sort.each do |cuisine| %>
          <li><%= cuisine %></li>
        <% end %>
      </ul>
    </dd>
  </dl>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Change a restaurant's details</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<%= link_to cuisines_path, title: 'List all participating restaurants by cuisine' do %>
  <h1>OpenTable <span>alternative</span></h1>
  <p>See all restaurants sorted by cuisine</p>
<% end %>
<%= render @restaurants %>
<% if current_user %>
  <%= link_to "New restaurant", new_restaurant_path %>
<% else %>
  <p>Please <%= login_link %> or <%= signup_link %> to add a restaurant.</p>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurant details</h1>
<% if current_user %>
  <%= link_to "Edit", edit_restaurant_path(@restaurant), title: "Change this restaurants's details" %>
  <%= link_to 'Delete', restaurant_path(@restaurant), title: "Delete this restaurant", :'data-method' => 'delete' %>
<% else %>
  <p>Please <%= login_link %> or <%= signup_link %> to change a restaurant.</p>
<% end %>
<%= render 'restaurants/restaurant', :restaurant => @restaurant %>

<%  num_reservations = @restaurant.reservations.count
    if num_reservations > 0 
%>
  <h2 id="reservations"><%= num_reservations %> Reservations</h2>
  <% @restaurant.reservations.each do |reservation| %>
    <% if current_user && reservation.id %>
      <%= link_to 'Edit', edit_restaurant_reservation_path(@restaurant, reservation), title: "Change this reservation" %>
      <%= link_to 'Cancel reservation', restaurant_reservation_path(@restaurant, reservation), title: "Cancel this reservation", :'data-method' => 'delete' %>
    <% end %>
    <% if reservation.user != nil %>
      <p><%= formatted_datetime(reservation.date_and_time) %> for <%= pluralize(reservation.size, "person") %></p>
    <% end %>
  <% end %>
  <h3>New reservation</h3>
<% else %>
  <h2>New reservation</h2>
  <p>Be the first to book with this restaurant!</p>
<% end %>

<!-- Show reservation form only if logged in -->
<% if current_user %>
  <%= render 'reservations/form' %>
<% else %>
  <p>Please <%= login_link %> or <%= signup_link %> to make a reservation.</p>
<% end %>